feat: verify basic workflow in QA env
GreptimeTeam/greptimedb-client-go pull request #49
Opened 2023-03-22 06:42 UTC by vinland-avalon

## What's changed and what's your intention?

- Use `username` and `password` to implement authorization
- Change the semantic of `Host` in config, since users of GCP do not know about port 4001

## Checklist

- [ ]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
- fix #48

2023-03-23 01:59 UTC, yuanbohan requested changes

2023-03-23 01:59 UTC, yuanbohan commented on examples/request.go
```
go run examples/request.go
```

```
fail to insert, err: name of database should not be empty
```

2023-03-23 01:59 UTC, yuanbohan commented on pkg/request/config.go
> +var gRPCPort string = "4001"
the port may be different in cloud? It may be better to behave like MySQL or Postgres, the port can be configured by the users. 

For example, users want to interact with on-premise GreptimeDB service, and the exported gRPC port is configured differently as 4001 by the Ops teams.

2023-03-23 01:59 UTC, yuanbohan commented on pkg/request/config.go
> +func NewCfgWithAddr(addr, catalog, database string) *Config {
This is not a good `Go` way to generate an instance. There are so many fields in the `Config` struct, why just expose these three parameters? What about no parameter in this function (just `NewCfg`), and config fields via `WithXXX` method?

2023-03-23 02:01 UTC, yuanbohan commented on examples/request.go
and do not forget to update the coding in README

2023-03-23 03:40 UTC, vinland-avalon commented on pkg/request/config.go
> +var gRPCPort string = "4001"
The GCP will not tell users which port they should use. `port` is  transparent to them. So I think providing two init function for two user group might help.

2023-03-23 03:42 UTC, vinland-avalon commented on examples/request.go
Ok. I will fill it with some parameters so users can insert to their local DB instance. And for the user guide, I'll revise them just before merging to master branch.

2023-03-23 03:55 UTC, vinland-avalon commented on pkg/request/config.go
> +func NewCfgWithAddr(addr, catalog, database string) *Config {
emmm... However, these three parameters are a must to build a `Config`. With a no-parameter one, users still have to set by themselves afterwards. So why not make them set these now?

2023-03-23 09:52 UTC, yuanbohan approved these changes
LGTM

2023-03-24 02:13 UTC, vinland-avalon commented
@yuanbohan I've made some revise to README.md to guide users connect DB with authentication. PTAL

2023-03-24 02:45 UTC, merged